import { Inter } from "next/font/google";
import Head from "next/head";
import Menu from "./components/menu";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="viewport" content="viewport-fit=cover" />
      </Head>
      <body className={inter.className}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
